name: pump_management_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  supabase_flutter: ^2.9.0
  flutter_tts: ^3.5.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  mobile_scanner: ^6.0.0
  flutter_dotenv: ^5.0.2
  permission_handler: ^11.0.0
  flutter_sound: ^9.2.15
  http: ^1.1.0
  flutter_chat_ui: ^1.5.6
  flutter_chat_types: ^3.5.7
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  geolocator: ^10.1.0
  geocoding: ^4.0.0
  json_annotation: ^4.8.1
  openai_realtime_dart: ^0.0.3+1
  pdf: ^3.10.7
  printing: ^5.11.1
  share_plus: ^7.2.1  
  open_file: ^3.3.2 
  url_launcher: ^6.2.2
  intl: ^0.18.1
  location : ^8.0.0
  file_picker: ^10.1.7
  path: ^1.8.3
  excel: ^4.0.6
  google_fonts: ^6.2.1
  lottie: ^3.2.2
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  scrollable_positioned_list: ^0.3.8
  syncfusion_flutter_pdf: ^29.2.7+1
  syncfusion_flutter_pdfviewer: ^29.2.7
  mailer: ^6.1.0
  app_links: ^6.4.0
  flutter_linkify: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.jpeg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
#    - assets/audio/
    - assets/animations/login_animation.json
    - assets/animations/Signup_animation.json
    - assets/animations/verification.json
    - .env
    - assets/images/ember_logo.png
    - assets/images/tecnvi-logo.jpg
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf